# Caroline Petersen 

## Question 1

Please write a python script that provides a printed output for the following arithmetic functions (you can use any numbers):<br>
Multiplication <br>
Division <br>
Addition<br>
Subtraction <br>
Modulo Operator

In [8]:
a = 4
b = 6
print(a * b)
print(a / b)
print(a + b)
print(a - b)
print(a % b)

24
0.6666666666666666
10
-2
4


## Question 2

Create an array with at least one of each data type. Create an array with only one data type. Compare the data types using a logical expression (equals, greater than or equal, not equal). Please have these values printed out.

In [37]:
array1 = ["Christmas", True, 679, 1.1, ['1', '2']]
array2 = [2,4,6,8,10]

equal = type(array1) == type(array2)
not_equal = type(array1) != type(array2)
is_array1_longer = len(array1) >= len(array2)

print(equal)
print(not_equal)
print(is_array1_longer)

True
False
True


## Question 3

Create a list and use a for loop to print out each element of that list.

In [10]:
fruits = ['apple', 'strawberry', 'banana', 'pear', 'orange']
for fruit in fruits:
    print(fruit)

apple
strawberry
banana
pear
orange


## Question 4

Create an array with numbers ranging from 1 to 100. Using a for loop, change the value of each even number in the total range of values to be equal to 0 within the array. Print out the final results as a table.

In [8]:
import numpy as np
from tabulate import tabulate

numbers = np.arange(1,101)
for i in range(len(numbers)):
    if numbers[i] % 2 == 0:
        numbers[i] = 0

headers = ["Index", "Value"]
data = [[i, value] for i, value in enumerate(numbers)]
table = tabulate(data, headers, tablefmt="grid")

print(table)

+---------+---------+
|   Index |   Value |
+=========+=========+
|       0 |       1 |
+---------+---------+
|       1 |       0 |
+---------+---------+
|       2 |       3 |
+---------+---------+
|       3 |       0 |
+---------+---------+
|       4 |       5 |
+---------+---------+
|       5 |       0 |
+---------+---------+
|       6 |       7 |
+---------+---------+
|       7 |       0 |
+---------+---------+
|       8 |       9 |
+---------+---------+
|       9 |       0 |
+---------+---------+
|      10 |      11 |
+---------+---------+
|      11 |       0 |
+---------+---------+
|      12 |      13 |
+---------+---------+
|      13 |       0 |
+---------+---------+
|      14 |      15 |
+---------+---------+
|      15 |       0 |
+---------+---------+
|      16 |      17 |
+---------+---------+
|      17 |       0 |
+---------+---------+
|      18 |      19 |
+---------+---------+
|      19 |       0 |
+---------+---------+
|      20 |      21 |
+---------+---------+
|      21 

## Question 5

Create a function that will print out a conversation between two people. Your function should accept two inputs: 1. The name of person A, and the name of Person B. Write your function so that if the name of Person A is less than 5 characters, Person B will reply with the line: “Wow, your name is so short!” (print the message to the console).<br>
Example:<br>
Person A: “Hi my name is ____”<br>
Person B: “Hello, person A name, my name is ____” Person B: “Wow, your name is so short!”

In [24]:
person_a_name = input()
person_b_name = input()
if len(person_a_name) < 5: 
    print(f"Hi my name is {person_a_name}.")
    print(f"Hello, {person_a_name}, my name is {person_b_name}.")
    print(f"Wow, your name is so short!")
if len(person_a_name) > 5: 
    print(f"Hi my name is {person_a_name}.")
    print(f"Hello, {person_a_name}, my name is {person_b_name}.")

Judy
Louis
Hi my name is Judy.
Hello, Judy, my name is Louis.
Wow, your name is so short!


## Question 6

Create two arrays that each have a random range of numbers from 1 to 50. Conduct the following arithmetic functions across the two arrays and print out the results:<br>
Multiplication<br> Division<br> Addition<br> Subtraction<br> Modulo Operator

In [31]:
import numpy as np

first = np.random.randint(1, 51, size=20)
second = np.random.randint(1, 51, size=20)

multiplication = first * second 
print(second)

division = first / second 
print(division)

addition = first + second 
print(addition)

subtraction = first - second
print(subtraction)

modulo_operator = first % second
print(modulo_operator)

[35 16 15 24 43  7 33  5 19  8 39 25  7 50 33 19 42 16 29  9]
[0.8        0.125      1.66666667 1.66666667 0.44186047 7.
 0.48484848 6.         2.63157895 2.875      0.64102564 0.2
 5.28571429 0.9        1.09090909 2.52631579 0.26190476 2.6875
 1.48275862 0.66666667]
[63 18 40 64 62 56 49 35 69 31 64 30 44 95 69 67 53 59 72 15]
[ -7 -14  10  16 -24  42 -17  25  31  15 -14 -20  30  -5   3  29 -31  27
  14  -3]
[28  2 10 16 19  0 16  0 12  7 25  5  2 45  3 10 11 11 14  6]


## Question 7

Create a dictionary that has key, value pairs for different types of foods. Create a similar function to Question 5’s function that prints out the value of a key based on input from a user.<br> 
Example:<br> 
“Please type your favorite food: “<br> 
User types: Pizza<br> 
Code response: “Ah, Pizza, we have pepperoni.” Where pepperoni is the value of the key.

In [33]:
print("Please type your favorite food:")

favorite_food = input()
food = {
    "fruit": "strawberries",
    "pizza": "cheese",
    "pasta": "alfredo",
    "ice cream": "vanilla",
    "cake": "lemon",
    "cookie": "snickerdoodle",
    "soda": "sprite",
    "pie": "apple",
    "chicken": "lemon pepper"
}

if favorite_food in food:
    print(f"Ah, {favorite_food}, we have {food[favorite_food]}.")
else:
    print(f"Sorry, we don't have {favorite_food}.")

Please type your favorite food:
salad
Sorry, we don't have salad.


## Question 8

Create a while loop that will continuously print a message until a specified value is reached.

In [18]:
value = 5 
while value < 50: 
    print(value)
    value += 5

5
10
15
20
25
30
35
40
45


## Question 8b

Create a while loop that runs a calculation on an array of numbers until the last value within the array has been run.

In [19]:
import numpy as np 

index = 0
array = np.arange(1,23)

while index < len(array): 
    result = array[index]*2
    print(result)
    index += 1

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44


## Question 9

Please explain the difference between a list, an array, and a dictionary and when you would use each one. (Type your answer as a comment or within a text cell).

Lists can store different data types but arrays only have elements from the same data type. Lists cannot have arithmetic operations applied to them, but arrays can. Arrays also need the importation of modules to perform functions on them, unlike lists. You would use a list when you need to store data and want flexibility in manipulating the elements—a to-list would be a perfect example. You can perform direct operations like append() to add tasks as well as remove() to remove tasks without having to import anything extra. Arrays are more handy for data-heavy operations. A dictionary in Python uses keys to look up values. Information is stored in pairs where each pair has a word/key and its meaning/value. These can be used when you need to quickly look up data by using specific labels or keys. 

## Question 10

Please explain the difference between logical operators and comparison operators and describe one use case for when they would be used (do not use the description from the lecture/lab materials - think through it):<br> 
If <br>Elif <br>Else<br> <br> 
==<br>
!=<br>
& (and)<br>
| (or)

Logical operators help you decide if certain statements are true or not. They can be used to verify whether several conditions are true, combine conditions, and more. “If” statements are used to run a code only if certain conditions are met. If the conditions are not met, then the code is not executed. "Else" statements come after if statements to state what happens if the if statement is false. "Elif" is short for "else if" and is used to check additional conditions. If the initial if statement is false but the elif statement below it is true, the elif statement will be executed. It works similarly to else statements as a failsafe to if statements. A simple way you can use this is to check if a value is greater than or equal to a number. If your number is 23 and you have the statement “if x > 23: print("x is greater than 23”)” it will not print. However, if this is followed by “elif x == 23: print("x is equal to 23”)” the code will execute and print that x is equal to 23 even though the first if statement was false.<br>
<br>
Comparison operators simply compare two values. They take two values or expressions to draw upon these comparisons and return either true or false as the output. You might use ‘==‘ when trying to determine if two expressions are equal. Similarly, you can use ‘!=‘ to see if two values do not equal each other. For instance, this can coincide with a conditional statement to see if “x != y” then you can print a different statement to execute a code when two values are not equal. Both &(and) and |(or) are used to combine conditional statements, however, they vary slightly. For instance, you can say “if a > b and c > a: print("Both conditions are true”)” but you can also say, “if a > b or c > a: print("Both conditions are true”).”